global using SolveIt.Common.Paging;
global using SolveIt.DataLayer.Context;
global using SolveIt.DataLayer.Repositories.Common;
global using SolveIt.Domain.Entities.Common;
global using SolveIt.Domain.Entities.Locations;
global using SolveIt.Domain.Interfaces.Accounts;
global using SolveIt.Domain.Interfaces.Common;
global using SolveIt.Domain.Interfaces.Locations;
global using SolveIt.Entities.Models.Users;
