//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolveIt.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolveIt.Common.Resources.PropertyDictionary", typeof(PropertyDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره من.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احراز هویت.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آواتار.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدال برنزی.
        /// </summary>
        public static string BronzeMedal {
            get {
                return ResourceManager.GetString("BronzeMedal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر کلمه عبور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر پیدا نشد.
        /// </summary>
        public static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمات عبور  یکسان نیست.
        /// </summary>
        public static string ComparePasswordErrorMessage {
            get {
                return ResourceManager.GetString("ComparePasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است. لطفا با ادمین تماس برقرار کنید.
        /// </summary>
        public static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور پیدا نشد.
        /// </summary>
        public static string CountryNotFound {
            get {
                return ResourceManager.GetString("CountryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب کنید.
        /// </summary>
        public static string DoChose {
            get {
                return ResourceManager.GetString("DoChose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پروفایل.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال سازی شده منقضی شده است. لینک جدید به ایمیل شما ارسال شد.مجددا از طریق آن لینک اقدام به فعال سازی کنید..
        /// </summary>
        public static string EmailActivationCodeHasBeenExpired {
            get {
                return ResourceManager.GetString("EmailActivationCodeHasBeenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل تکراری است..
        /// </summary>
        public static string EmailIsDuplicate {
            get {
                return ResourceManager.GetString("EmailIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل و یا شماره موبایل.
        /// </summary>
        public static string EmailOrMobile {
            get {
                return ResourceManager.GetString("EmailOrMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل با موفقیت فعال شد..
        /// </summary>
        public static string EmailSuccessfullyActivated {
            get {
                return ResourceManager.GetString("EmailSuccessfullyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل تنها با فرمت های زیر قابل قبول است..
        /// </summary>
        public static string FileFormatAllowedAsBelow {
            get {
                return ResourceManager.GetString("FileFormatAllowedAsBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایلی انتخاب نشده است.
        /// </summary>
        public static string FileIsEmpty {
            get {
                return ResourceManager.GetString("FileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراموشی کلمه عبور.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت خبرنامه.
        /// </summary>
        public static string GetNewsLetter {
            get {
                return ResourceManager.GetString("GetNewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعلان.
        /// </summary>
        public static string GnAlert {
            get {
                return ResourceManager.GetString("GnAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده معتبر نمی باشد..
        /// </summary>
        public static string GnEmailFormatErrorMessage {
            get {
                return ResourceManager.GetString("GnEmailFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل حداکثر میتواند {0} باشد..
        /// </summary>
        public static string GnFileSizeError {
            get {
                return ResourceManager.GetString("GnFileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول {0} برابر {1} کاراکتر است..
        /// </summary>
        public static string GnMaxLengthErrorMessage {
            get {
                return ResourceManager.GetString("GnMaxLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل طول {0} برابر {1} کاراکتر است..
        /// </summary>
        public static string GnMinLengthErrorMessage {
            get {
                return ResourceManager.GetString("GnMinLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باشه.
        /// </summary>
        public static string GnOk {
            get {
                return ResourceManager.GetString("GnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string GnOperationSuccessfulltDone {
            get {
                return ResourceManager.GetString("GnOperationSuccessfulltDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا {0} را وارد کنید..
        /// </summary>
        public static string GnRequiredErrorMessage {
            get {
                return ResourceManager.GetString("GnRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است.
        /// </summary>
        public static string GnSomethingWenWrong {
            get {
                return ResourceManager.GetString("GnSomethingWenWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string GnSubmit {
            get {
                return ResourceManager.GetString("GnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدال طلایی.
        /// </summary>
        public static string GoldMedal {
            get {
                return ResourceManager.GetString("GoldMedal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور خود را فراموش کرده ام!.
        /// </summary>
        public static string IHaveForgotPassword {
            get {
                return ResourceManager.GetString("IHaveForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور صحیح نیست..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنها فرمت ایمیل و موبایل قابل قبول است..
        /// </summary>
        public static string InputEmailOrMobileFormatIsWrong {
            get {
                return ResourceManager.GetString("InputEmailOrMobileFormatIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان شغلی.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string LandingPage {
            get {
                return ResourceManager.GetString("LandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با اطلاعات وارد شده کاربری یافت نشد.
        /// </summary>
        public static string LoginInputIsNotValid {
            get {
                return ResourceManager.GetString("LoginInputIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری.
        /// </summary>
        public static string LoginToAccount {
            get {
                return ResourceManager.GetString("LoginToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال سازی شده منقضی شده است. کد جدید به موبایل شما ارسال شد.مجددا از طریق آن لینک اقدام به فعال سازی کنید..
        /// </summary>
        public static string MobileActivationCodeHasBeenExpired {
            get {
                return ResourceManager.GetString("MobileActivationCodeHasBeenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت موبایل صحیح نیست..
        /// </summary>
        public static string MobileFormatIsNotCorrect {
            get {
                return ResourceManager.GetString("MobileFormatIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارده شده تکراری است..
        /// </summary>
        public static string MobileIsDuplicate {
            get {
                return ResourceManager.GetString("MobileIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل با موفقیت فعال شد.
        /// </summary>
        public static string MobileSuccessfullyActivated {
            get {
                return ResourceManager.GetString("MobileSuccessfullyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون مدال.
        /// </summary>
        public static string NoMedal {
            get {
                return ResourceManager.GetString("NoMedal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور فعلی.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور خالی است..
        /// </summary>
        public static string PasswordCantBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور باید شامل عدد باشد.
        /// </summary>
        public static string PasswordMustContainDigit {
            get {
                return ResourceManager.GetString("PasswordMustContainDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور باید شامل حداقل 1 حرف کوچک باشد.
        /// </summary>
        public static string PasswordMustContainLowerCase {
            get {
                return ResourceManager.GetString("PasswordMustContainLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور باید شامل کاراکتر های ویژه باشد.
        /// </summary>
        public static string PasswordMustContainSpecialChar {
            get {
                return ResourceManager.GetString("PasswordMustContainSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور باید شامل حداقل 1 حرف بزرگ باشد.
        /// </summary>
        public static string PasswordMustContainUpperCase {
            get {
                return ResourceManager.GetString("PasswordMustContainUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت تاریخ صحیح نیست.
        /// </summary>
        public static string PersianDateIsNotInFormat {
            get {
                return ResourceManager.GetString("PersianDateIsNotInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام در سایت.
        /// </summary>
        public static string RegisterInSite {
            get {
                return ResourceManager.GetString("RegisterInSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام با موفقت انجام شد.  جهت فعال سازی اکانت ایمیل خود را چک کنید..
        /// </summary>
        public static string RegisterSuccessfullyDoneMessageForEmail {
            get {
                return ResourceManager.GetString("RegisterSuccessfullyDoneMessageForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام با موفقت انجام شد.  جهت فعال سازی کد ارسال شده به مویایلتان را وارد کنید.
        /// </summary>
        public static string RegisterSuccessfullyDoneMessageForMobile {
            get {
                return ResourceManager.GetString("RegisterSuccessfullyDoneMessageForMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور جدید.
        /// </summary>
        public static string ReNewPassword {
            get {
                return ResourceManager.GetString("ReNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        public static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به صفحه اصلی.
        /// </summary>
        public static string RerurnHome {
            get {
                return ResourceManager.GetString("RerurnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی کلمه عبور.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیلی حاوی لینک ریست پسورد برای شما ارسال شد..
        /// </summary>
        public static string ResetPasswordLinkSentByEmail {
            get {
                return ResourceManager.GetString("ResetPasswordLinkSentByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت تکمیل ریست کردن کلمه عبور کدی که برای موبایلتان ارسال شد..
        /// </summary>
        public static string ResetPasswordVerificationCodeSentByMobile {
            get {
                return ResourceManager.GetString("ResetPasswordVerificationCodeSentByMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدال نقره ای.
        /// </summary>
        public static string SilverMedal {
            get {
                return ResourceManager.GetString("SilverMedal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مسدود شده است. برای اطلاع بیشتر با ادمین تماس بگیرید.
        /// </summary>
        public static string UserIsBan {
            get {
                return ResourceManager.GetString("UserIsBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت شما فعال نشده است.  ایمیل فعال سازی مجددا برای شما ارسال شد.
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل کاربری.
        /// </summary>
        public static string UserPanel {
            get {
                return ResourceManager.GetString("UserPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد احراز هویت.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
    }
}
