global using SolveIt.Application.Services.Interfaces.Accounts;
global using SolveIt.Application.ViewModels.Accounts;
global using SolveIt.Common.OperationResult;
global using SolveIt.DataLayer.Context;
global using SolveIt.Entities.Models.Users;
global using SolveIt.IoC;
global using SolveIt.Web.ActionFilters;
global using SolveIt.Web.Extensions;
global using SolveIt.Web.Extensions.Registers;
